

package CasosDeUso.Informes;

import CasosDeUso.Exepciones.ManejoExcepciones;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sistemacompraproveedores.DTO.DTOCabeceraRanking;
import sistemacompraproveedores.DTO.DTORankingProveedor;

public class RankearProveedor4 extends javax.swing.JFrame {
    PdfPTable tablapdf= new PdfPTable(4);
    Date today = new Date();
    DateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
    DateFormat formatohora = new SimpleDateFormat("HH:mm:ss");
    DecimalFormat decimal = new DecimalFormat("0.00");
    private Date fechadesde;
    private Date fechahasta;
    private boolean direcionbandera = true;
    
    
    public RankearProveedor4() {
        initComponents();
    }
    public RankearProveedor4(DTOCabeceraRanking dtocabecera, Date desde, Date hasta){
        initComponents();
        fechadesde = desde; fechahasta = hasta;
        this.setTitle("Guardar Informe en PDF");
        this.setLocationRelativeTo(null);
        PdfPCell puestocell = new PdfPCell(new Phrase("Puesto"));
        PdfPCell proveedorcell= new PdfPCell(new Phrase("Proveedor"));
        PdfPCell codigoproveedorcell= new PdfPCell(new Phrase("Codigo Proveedor"));
        PdfPCell descuentoproveedorcell= new PdfPCell(new Phrase("Descuento"));
        puestocell.setBackgroundColor(BaseColor.LIGHT_GRAY);
        puestocell.setHorizontalAlignment(1);
        proveedorcell.setBackgroundColor(BaseColor.LIGHT_GRAY);
        proveedorcell.setHorizontalAlignment(1);
        codigoproveedorcell.setBackgroundColor(BaseColor.LIGHT_GRAY);
        codigoproveedorcell.setHorizontalAlignment(1);
        descuentoproveedorcell.setBackgroundColor(BaseColor.LIGHT_GRAY);
        descuentoproveedorcell.setHorizontalAlignment(1);
        tablapdf.addCell(puestocell);
        tablapdf.addCell(proveedorcell);
        tablapdf.addCell(codigoproveedorcell);
        tablapdf.addCell(descuentoproveedorcell);
        Integer i=1;
        for(DTORankingProveedor dtolist : dtocabecera.getM_DTORankingProveedorlist()){
            PdfPCell puesto = new PdfPCell(new Phrase(i.toString())); i++;
            puesto.setHorizontalAlignment(1);
            PdfPCell proveedor = new PdfPCell(new Phrase(dtolist.getNombreProveedor()));
            proveedor.setHorizontalAlignment(1);
            PdfPCell codigoproveedor = new PdfPCell(new Phrase(dtolist.getCodigoProveedor()));
            codigoproveedor.setHorizontalAlignment(1);
            PdfPCell descuentoproveedor = new PdfPCell(new Phrase(decimal.format(dtolist.getTotalDescuento())+"%"));
            descuentoproveedor.setHorizontalAlignment(1);
            tablapdf.addCell(puesto);
            tablapdf.addCell(proveedor);
            tablapdf.addCell(codigoproveedor);
            tablapdf.addCell(descuentoproveedor);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDireccion = new javax.swing.JTextField();
        jButtonDireccion = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldDireccion.setEditable(false);
        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });

        jButtonDireccion.setText("Direccion");
        jButtonDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDireccionActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDireccionActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        int opcion = jfc.showSaveDialog(this);
        if(opcion == JFileChooser.APPROVE_OPTION){
            File file = jfc.getSelectedFile();
            String fileString = file.toString();
            jTextFieldDireccion.setText(fileString);}
            direcionbandera = false;
        
        
        
        
    }//GEN-LAST:event_jButtonDireccionActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        String direccion = jTextFieldDireccion.getText();
        System.out.println("Valor direccion "+direccion);

try{
	if(direcionbandera) throw new ManejoExcepciones("Falta Direccion Archivo");
        FileOutputStream archivo = new FileOutputStream(direccion+".pdf");
	Document doc = new Document();
	PdfWriter.getInstance(doc, archivo);
	doc.open();
        doc.add(new Phrase("Informe Rankear Proveedor"));
        doc.add(new Phrase("     "));
        doc.add(new Phrase("Ranking desde "+String.valueOf(formatofecha.format(fechadesde))+" hasta "+String.valueOf(formatofecha.format(fechahasta))));
        doc.add(new com.itextpdf.text.pdf.PdfPTable(tablapdf));
	doc.add(new Phrase("Fecha de Constulta: "+String.valueOf(formatofecha.format(today)+"             Hora de consulta: "+String.valueOf(formatohora.format(today)))));
        doc.close();
	JOptionPane.showMessageDialog(null,"Documento creado con exito");
        this.setVisible(false);

}catch(ManejoExcepciones me){ if(me.getParametro()=="Falta Direccion Archivo"){
        JOptionPane.showMessageDialog(null, "Ingrese direccion donde desea guardar el achivo");}
}
 
 catch(Exception e){System.out.println("Error "+e);}

        
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankearProveedor4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankearProveedor4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankearProveedor4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankearProveedor4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankearProveedor4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDireccion;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JTextField jTextFieldDireccion;
    // End of variables declaration//GEN-END:variables
}
