/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacompraproveedores;

import CasosDeUso.Informes.CalcularCantidadPromedioDeEventosDeReposicion;
import CasosDeUso.Informes.GenerarEstadisticasSobrePorcentajeDeCotizacionesPromedio;
import CasosDeUso.Informes.GenerarInformeDePedidoConRechazosReiterados;
import CasosDeUso.Informes.RankearProveedor;

/**
 *
 * @author Gustavo
 */
public class Informes extends javax.swing.JFrame {

    /**
     * Creates new form Informes
     */
    public Informes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRanking = new javax.swing.JButton();
        btnCotiPro = new javax.swing.JButton();
        btnPedidoR = new javax.swing.JButton();
        btnEventosRepo = new javax.swing.JButton();
        btnExitInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA COMPRA A PROVEEDORES");

        btnRanking.setText("Ranking Proveedor");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });

        btnCotiPro.setText("Cotizaciones Promedio");
        btnCotiPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotiProActionPerformed(evt);
            }
        });

        btnPedidoR.setText("Pedidos Rechazados");
        btnPedidoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoRActionPerformed(evt);
            }
        });

        btnEventosRepo.setText("Eventos Reposición");
        btnEventosRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosRepoActionPerformed(evt);
            }
        });

        btnExitInfo.setText("Salir");
        btnExitInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPedidoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCotiPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEventosRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnExitInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRanking)
                    .addComponent(btnCotiPro))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedidoR)
                    .addComponent(btnEventosRepo))
                .addGap(18, 18, 18)
                .addComponent(btnExitInfo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitInfoActionPerformed
        this.setVisible(false);
                new Sistema().setVisible(true);
    }//GEN-LAST:event_btnExitInfoActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        this.setVisible(false);
                new RankearProveedor().setVisible(true);
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnCotiProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotiProActionPerformed
this.setVisible(false);
                new GenerarEstadisticasSobrePorcentajeDeCotizacionesPromedio().setVisible(true);
    }//GEN-LAST:event_btnCotiProActionPerformed

    private void btnPedidoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoRActionPerformed
this.setVisible(false);
                new GenerarInformeDePedidoConRechazosReiterados().setVisible(true);
    }//GEN-LAST:event_btnPedidoRActionPerformed

    private void btnEventosRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosRepoActionPerformed
        this.setVisible(false);
                new CalcularCantidadPromedioDeEventosDeReposicion().setVisible(true);
    }//GEN-LAST:event_btnEventosRepoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCotiPro;
    private javax.swing.JButton btnEventosRepo;
    private javax.swing.JButton btnExitInfo;
    private javax.swing.JButton btnPedidoR;
    private javax.swing.JButton btnRanking;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
